openapi: 3.2.0
info:
  title: Coveo Search Usage Metrics Service Search Hub Entitlement Sync API
  version: 1.0.0
  description: Documentation for Coveo Search Usage Metrics Service
  termsOfService: http://www.coveo.com/en/support/terms-agreements
  contact:
    name: ''
    url: ''
    email: support@coveo.com
  license:
    name: ''
    url: ''
servers:
- url: https://platform.cloud.coveo.com
  description: Coveo public API endpoint
tags:
- name: Search Hub Entitlement Sync
paths:
  /internal/jobs/trigger-searchhubs-entitlement-sync:
    post:
      operationId: triggerSearchHubEntitlementSyncJob
      summary: Trigger the AutoSearchHubEntitlementSyncJob to Run Asynchronously
      tags:
      - Search Hub Entitlement Sync
      deprecated: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchHubEntitlementSyncTriggerJobResponse'
      security:
      - oauth2:
        - full
components:
  schemas:
    SearchHubEntitlementSyncTriggerJobResponse:
      type: object
      properties:
        message:
          type: string
        jobKey:
          type: string
      required:
      - message
      - jobKey
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        implicit:
          scopes:
            full: full
          authorizationUrl: https://platform.cloud.coveo.com/oauth/authorize
      description: OAuth2
