naftiko: 1.0.0-alpha2
info:
  label: Coveo Commerce API — Listing Configurations
  description: 'Coveo Commerce API — Listing Configurations. 10 operations. Lead operation: Retrieves All Listing Configurations
    of an Organization. WILL BE DEPRECATED on 2026-08-31.. Self-contained Naftiko capability covering one Coveo business surface.'
  tags:
  - Coveo
  - Commerce
  - Listing Configurations
  created: '2026-05-19'
  modified: '2026-05-19'
binds:
- namespace: env
  keys:
    COVEO_SEARCH_TOKEN: COVEO_SEARCH_TOKEN
capability:
  consumes:
  - type: http
    namespace: commerce-listing-configurations
    baseUri: https://platform.cloud.coveo.com
    description: Coveo Commerce API — Listing Configurations business capability. Self-contained, no shared references.
    authentication:
      type: bearer
      token: '{{env.COVEO_SEARCH_TOKEN}}'
    resources:
    - name: rest-organizations-organizationId-commerce-v2-configurations-listings
      path: /rest/organizations/{organizationId}/commerce/v2/configurations/listings
      operations:
      - name: getall
        method: GET
        description: Retrieves All Listing Configurations of an Organization. WILL BE DEPRECATED on 2026-08-31.
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `acmecorporation8tp8wu3`
          required: true
        - name: trackingId
          in: query
          type: string
          description: The unique identifier of the tracking target.
          required: true
        - name: query
          in: query
          type: string
          description: Filter on names when requesting listing configuration names & IDs. Will perform '*query*' match pattern.
        - name: page
          in: query
          type: integer
          description: The 0-based index number of the page of listing configurations to retrieve.</br>**Minimum:** `0`</br>**Default:**
            `0`
        - name: perPage
          in: query
          type: integer
          description: The number of listing configurations to list per page.</br>**Minimum:** `1`</br>**Maximum:** `1000`</br>**Default:**
            `10`
      - name: create3
        method: POST
        description: Create a Listing Configuration. WILL BE DEPRECATED on 2026-08-31.
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `acmecorporation8tp8wu3`
          required: true
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
    - name: rest-organizations-organizationId-commerce-v2-configurations-listings-global
      path: /rest/organizations/{organizationId}/commerce/v2/configurations/listings/global
      operations:
      - name: getglobal1
        method: GET
        description: Retrieves the Global Listing Configuration for the Organization
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `acmecorporation8tp8wu3`
          required: true
        - name: trackingId
          in: query
          type: string
          description: The unique identifier of the tracking target.
          required: true
      - name: updateglobal1
        method: PUT
        description: Update the Global Listing Configuration for the Organization
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `acmecorporation8tp8wu3`
          required: true
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
    - name: rest-organizations-organizationId-commerce-v2-configurations-listings-names
      path: /rest/organizations/{organizationId}/commerce/v2/configurations/listings/names
      operations:
      - name: getallnames
        method: GET
        description: Retrieves All Listing Configurations Ids & Names of an Organization. WILL BE DEPRECATED on 2026-08-31.
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `acmecorporation8tp8wu3`
          required: true
        - name: trackingId
          in: query
          type: string
          description: The unique identifier of the tracking target.
          required: true
        - name: query
          in: query
          type: string
          description: Filter on names when requesting listing configuration names & IDs. Will perform '*query*' match pattern.
        - name: page
          in: query
          type: integer
          description: The 0-based index number of the page of listing configurations to retrieve.</br>**Minimum:** `0`</br>**Default:**
            `0`
        - name: perPage
          in: query
          type: integer
          description: The number of listing configurations to list per page.</br>**Minimum:** `1`</br>**Maximum:** `1000`</br>**Default:**
            `10`
    - name: rest-organizations-organizationId-commerce-v2-configurations-listings-rules
      path: /rest/organizations/{organizationId}/commerce/v2/configurations/listings/rules
      operations:
      - name: getrules
        method: GET
        description: Retrieves All Rules Related to Listings of an Organization. WILL BE DEPRECATED on 2026-08-31.
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `acmecorporation8tp8wu3`
          required: true
        - name: trackingId
          in: query
          type: string
          description: The unique identifier of the tracking target.
          required: true
        - name: configurationId
          in: query
          type: string
          description: The unique identifier of the listing configuration.
        - name: name
          in: query
          type: string
          description: Filter on rule name when requesting rules.
        - name: scope
          in: query
          type: string
          description: 'Rule scope to return. One of: [specific, global]. Returns all if not specified.'
        - name: essential
          in: query
          type: boolean
          description: Indicates if the rule is essential to the listing page; the essential rule is added during page creation.
            Returns all rules if not specified.
        - name: language
          in: query
          type: string
          description: An ISO 639-1 language code.
        - name: country
          in: query
          type: string
          description: An ISO 3166-1 alpha-2 country code.
        - name: currency
          in: query
          type: string
          description: An ISO 4217 currency code.
        - name: actions
          in: query
          type: array
          description: 'Rule action type to return. One of: [boost, bury, pin, include, exclude, onlyShow]. Returns all if
            not specified.'
        - name: sort
          in: query
          type: array
          description: List of property.direction to sort by
        - name: scheduleFilter
          in: query
          type: string
          description: The schedule filter to apply.
        - name: page
          in: query
          type: integer
          description: The 0-based index number of the page of rules to retrieve.</br>**Minimum:** `0`</br>**Default:** `0`
        - name: perPage
          in: query
          type: integer
          description: The number of rules to list per page.</br>**Minimum:** `1`</br>**Maximum:** `1000`</br>**Default:**
            `10`
    - name: rest-organizations-organizationId-commerce-v2-configurations-listings-url
      path: /rest/organizations/{organizationId}/commerce/v2/configurations/listings/url
      operations:
      - name: getbyurl
        method: GET
        description: Retrieves a Listing Configuration by Its Matching Url. WILL BE DEPRECATED on 2026-08-31.
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `acmecorporation8tp8wu3`
          required: true
        - name: trackingId
          in: query
          type: string
          description: The unique identifier of the tracking target.
          required: true
        - name: url
          in: query
          type: string
          description: URL
          required: true
    - name: rest-organizations-organizationId-commerce-v2-configurations-listings-configurat
      path: /rest/organizations/{organizationId}/commerce/v2/configurations/listings/{configurationId}
      operations:
      - name: get3
        method: GET
        description: Retrieves a Listing Configuration. WILL BE DEPRECATED on 2026-08-31.
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `acmecorporation8tp8wu3`
          required: true
        - name: configurationId
          in: path
          type: string
          description: The unique identifier of the listing configuration.
          required: true
      - name: update3
        method: PUT
        description: Update a Listing Configuration. WILL BE DEPRECATED on 2026-08-31.
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `acmecorporation8tp8wu3`
          required: true
        - name: configurationId
          in: path
          type: string
          description: The unique identifier of the listing configuration.
          required: true
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
      - name: delete3
        method: DELETE
        description: Deletes a Listing Configuration. WILL BE DEPRECATED on 2026-08-31.
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `acmecorporation8tp8wu3`
          required: true
        - name: configurationId
          in: path
          type: string
          description: The unique identifier of the listing configuration.
          required: true
