naftiko: 1.0.0-alpha2
info:
  label: Coveo Commerce API — Recommendations Configuration
  description: 'Coveo Commerce API — Recommendations Configuration. 12 operations. Lead operation: Retrieves All Slot Configurations
    of an Organization. Self-contained Naftiko capability covering one Coveo business surface.'
  tags:
  - Coveo
  - Commerce
  - Recommendations Configuration
  created: '2026-05-19'
  modified: '2026-05-19'
binds:
- namespace: env
  keys:
    COVEO_SEARCH_TOKEN: COVEO_SEARCH_TOKEN
capability:
  consumes:
  - type: http
    namespace: commerce-recommendations-configuration
    baseUri: https://platform.cloud.coveo.com
    description: Coveo Commerce API — Recommendations Configuration business capability. Self-contained, no shared references.
    authentication:
      type: bearer
      token: '{{env.COVEO_SEARCH_TOKEN}}'
    resources:
    - name: rest-organizations-organizationId-commerce-v2-recommendations-slots
      path: /rest/organizations/{organizationId}/commerce/v2/recommendations/slots
      operations:
      - name: getslotconfigurations
        method: GET
        description: Retrieves All Slot Configurations of an Organization
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `acmecorporation8tp8wu3`
          required: true
        - name: trackingId
          in: query
          type: string
          description: The unique identifier of the tracking target.
          required: true
        - name: page
          in: query
          type: integer
          description: The 0-based index number of the page of [slot configuration](https://docs.coveo.com/en/o9b80563/glossary/recommendation-slot/)
            to retrieve.</br>**Minimum:** `0`
        - name: perPage
          in: query
          type: integer
          description: The number of [slot configurations](https://docs.coveo.com/en/o9b80563/glossary/recommendation-slot/)
            to list per page.</br>**Minimum:** `1`</br>**Maximum:** `1
      - name: createslotconfiguration
        method: POST
        description: Create a Slot Configuration
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `acmecorporation8tp8wu3`
          required: true
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
    - name: rest-organizations-organizationId-commerce-v2-recommendations-slots-global-query
      path: /rest/organizations/{organizationId}/commerce/v2/recommendations/slots/global/query-configuration
      operations:
      - name: getglobalqueryconfiguration
        method: GET
        description: Retrieves a Global Query Configuration
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `acmecorporation8tp8wu3`
          required: true
        - name: trackingId
          in: query
          type: string
          description: The unique identifier of the tracking target.
          required: true
      - name: updateglobalqueryconfiguration
        method: PUT
        description: Update a Global Query Configuration
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `acmecorporation8tp8wu3`
          required: true
        - name: trackingId
          in: query
          type: string
          description: The unique identifier of the tracking target.
          required: true
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
    - name: rest-organizations-organizationId-commerce-v2-recommendations-slots-names
      path: /rest/organizations/{organizationId}/commerce/v2/recommendations/slots/names
      operations:
      - name: getslotconfigurationnames
        method: GET
        description: Retrieves All Slot Configuration Ids & Names of an Organization
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `acmecorporation8tp8wu3`
          required: true
        - name: trackingId
          in: query
          type: string
          description: The unique identifier of the tracking target.
          required: true
        - name: query
          in: query
          type: string
          description: Filter on names when requesting slot names & IDs. Will perform '*query*' match pattern.
        - name: page
          in: query
          type: integer
          description: The 0-based index number of the page of [slot configuration](https://docs.coveo.com/en/o9b80563/glossary/recommendation-slot/)
            to retrieve.</br>**Minimum:** `0`
        - name: perPage
          in: query
          type: integer
          description: The number of [slot configurations](https://docs.coveo.com/en/o9b80563/glossary/recommendation-slot/)
            to list per page.</br>**Minimum:** `1`</br>**Maximum:** `1
    - name: rest-organizations-organizationId-commerce-v2-recommendations-slots-strategies
      path: /rest/organizations/{organizationId}/commerce/v2/recommendations/slots/strategies
      operations:
      - name: getslotstrategies1
        method: GET
        description: Retrieves Available Slot Strategies
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `acmecorporation8tp8wu3`
          required: true
        - name: slotType
          in: query
          type: string
          description: A slot type label that identifies the location of a slot.
          required: true
        - name: seedType
          in: query
          type: string
          description: 'The primary [seed product](https://docs.coveo.com/en/n5jg0219/glossary/seed-product) type used by
            recommendations strategies on this [slot configuration](https:'
          required: true
    - name: rest-organizations-organizationId-commerce-v2-recommendations-slots-configuratio
      path: /rest/organizations/{organizationId}/commerce/v2/recommendations/slots/{configurationId}
      operations:
      - name: getslotconfiguration
        method: GET
        description: Retrieves a Slot Configuration
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `acmecorporation8tp8wu3`
          required: true
        - name: configurationId
          in: path
          type: string
          description: The unique identifier of the [slot configuration](https://docs.coveo.com/en/o9b80563/glossary/recommendation-slot/).
          required: true
      - name: updateslotconfiguration
        method: PUT
        description: Update a Slot Configuration
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `acmecorporation8tp8wu3`
          required: true
        - name: configurationId
          in: path
          type: string
          description: The unique identifier of the [slot configuration](https://docs.coveo.com/en/o9b80563/glossary/recommendation-slot/).
          required: true
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
      - name: deleteslotconfiguration
        method: DELETE
        description: Deletes a Slot Configuration
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `acmecorporation8tp8wu3`
          required: true
        - name: configurationId
          in: path
          type: string
          description: The unique identifier of the [slot configuration](https://docs.coveo.com/en/o9b80563/glossary/recommendation-slot/).
          required: true
    - name: rest-organizations-organizationId-commerce-v2-recommendations-slots-configuratio
      path: /rest/organizations/{organizationId}/commerce/v2/recommendations/slots/{configurationId}/settings
      operations:
      - name: getslotsettings
        method: GET
        description: Retrieves Slot Settings
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `acmecorporation8tp8wu3`
          required: true
        - name: configurationId
          in: path
          type: string
          description: The unique identifier of the [slot configuration](https://docs.coveo.com/en/o9b80563/glossary/recommendation-slot/).
          required: true
      - name: updateslotsettings
        method: PUT
        description: Update Slot Settings
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `acmecorporation8tp8wu3`
          required: true
        - name: configurationId
          in: path
          type: string
          description: The unique identifier of the [slot configuration](https://docs.coveo.com/en/o9b80563/glossary/recommendation-slot/).
          required: true
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
    - name: rest-organizations-organizationId-commerce-v2-recommendations-slots-configuratio
      path: /rest/organizations/{organizationId}/commerce/v2/recommendations/slots/{configurationId}/strategies
      operations:
      - name: getslotstrategies
        method: GET
        description: Retrieves Available Slot Strategies
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `acmecorporation8tp8wu3`
          required: true
        - name: configurationId
          in: path
          type: string
          description: The unique identifier of the [slot configuration](https://docs.coveo.com/en/o9b80563/glossary/recommendation-slot/).
          required: true
