naftiko: 1.0.0-alpha2
info:
  label: Coveo Commerce API — Product Suggest Configurations
  description: 'Coveo Commerce API — Product Suggest Configurations. 4 operations. Lead operation: Retrieves a Product Suggest
    Configuration. Self-contained Naftiko capability covering one Coveo business surface.'
  tags:
  - Coveo
  - Commerce
  - Product Suggest Configurations
  created: '2026-05-19'
  modified: '2026-05-19'
binds:
- namespace: env
  keys:
    COVEO_SEARCH_TOKEN: COVEO_SEARCH_TOKEN
capability:
  consumes:
  - type: http
    namespace: commerce-product-suggest-configurations
    baseUri: https://platform.cloud.coveo.com
    description: Coveo Commerce API — Product Suggest Configurations business capability. Self-contained, no shared references.
    authentication:
      type: bearer
      token: '{{env.COVEO_SEARCH_TOKEN}}'
    resources:
    - name: rest-organizations-organizationId-commerce-v2-configurations-productSuggest
      path: /rest/organizations/{organizationId}/commerce/v2/configurations/productSuggest
      operations:
      - name: get2
        method: GET
        description: Retrieves a Product Suggest Configuration
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `acmecorporation8tp8wu3`
          required: true
        - name: trackingId
          in: query
          type: string
          description: Tracking ID of the product suggest configuration
          required: true
      - name: update2
        method: PUT
        description: Update a Product Suggest Configuration
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `acmecorporation8tp8wu3`
          required: true
        - name: trackingId
          in: query
          type: string
          description: Tracking ID of the product suggest configuration
          required: true
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
      - name: create1
        method: POST
        description: Create a Product Suggest Configuration
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `acmecorporation8tp8wu3`
          required: true
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
      - name: delete2
        method: DELETE
        description: Deletes a Product Suggest Configuration
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `acmecorporation8tp8wu3`
          required: true
        - name: trackingId
          in: query
          type: string
          description: Tracking ID of the product suggest configuration
          required: true
