naftiko: 1.0.0-alpha2
info:
  label: Coveo Machine Learning Configuration API — Model Listing
  description: 'Coveo Machine Learning Configuration API — Model Listing. 2 operations. Lead operation: List Models. Self-contained
    Naftiko capability covering one Coveo business surface.'
  tags:
  - Coveo
  - Machine Learning Configuration
  - Model Listing
  created: '2026-05-19'
  modified: '2026-05-19'
binds:
- namespace: env
  keys:
    COVEO_API_KEY: COVEO_API_KEY
capability:
  consumes:
  - type: http
    namespace: ml-config-model-listing
    baseUri: https://platform.cloud.coveo.com
    description: Coveo Machine Learning Configuration API — Model Listing business capability. Self-contained, no shared references.
    authentication:
      type: bearer
      token: '{{env.COVEO_API_KEY}}'
    resources:
    - name: rest-organizations-organizationId-machinelearning-configuration-modellisting
      path: /rest/organizations/{organizationId}/machinelearning/configuration/modellisting
      operations:
      - name: getmodels
        method: GET
        description: List Models
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `mycoveocloudv2organizationg8tp8wu3`
          required: true
        - name: engineIds
          in: query
          type: array
          description: The engine identifiers of the machine learning models to request.
      - name: getmodels1
        method: POST
        description: List Models
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `mycoveocloudv2organizationg8tp8wu3`
          required: true
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
