naftiko: 1.0.0-alpha2
info:
  label: Coveo Machine Learning Configuration API — Case Classification Configuration
  description: 'Coveo Machine Learning Configuration API — Case Classification Configuration. 4 operations. Lead operation:
    Get CC Content Fields. Self-contained Naftiko capability covering one Coveo business surface.'
  tags:
  - Coveo
  - Machine Learning Configuration
  - Case Classification Configuration
  created: '2026-05-19'
  modified: '2026-05-19'
binds:
- namespace: env
  keys:
    COVEO_API_KEY: COVEO_API_KEY
capability:
  consumes:
  - type: http
    namespace: ml-config-case-classification-configuration
    baseUri: https://platform.cloud.coveo.com
    description: Coveo Machine Learning Configuration API — Case Classification Configuration business capability. Self-contained,
      no shared references.
    authentication:
      type: bearer
      token: '{{env.COVEO_API_KEY}}'
    resources:
    - name: rest-organizations-organizationId-machinelearning-configuration-caseclassif-fiel
      path: /rest/organizations/{organizationId}/machinelearning/configuration/caseclassif/fields
      operations:
      - name: getfields
        method: POST
        description: Get CC Content Fields
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `mycoveocloudv2organizationg8tp8wu3`
          required: true
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
    - name: rest-organizations-organizationId-machinelearning-configuration-caseclassif-fiel
      path: /rest/organizations/{organizationId}/machinelearning/configuration/caseclassif/fields/{fieldName}/documentCount
      operations:
      - name: getdocumentcountforfield
        method: POST
        description: <details><summary>Privilege required</summary>
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `mycoveocloudv2organizationg8tp8wu3`
          required: true
        - name: fieldName
          in: path
          type: string
          description: Name of the field
          required: true
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
    - name: rest-organizations-organizationId-machinelearning-configuration-caseclassif-fiel
      path: /rest/organizations/{organizationId}/machinelearning/configuration/caseclassif/fields/{fieldName}/valueCount
      operations:
      - name: getvaluecountforfield
        method: POST
        description: <details><summary>Privilege required</summary>
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `mycoveocloudv2organizationg8tp8wu3`
          required: true
        - name: fieldName
          in: path
          type: string
          description: Name of the field
          required: true
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
    - name: rest-organizations-organizationId-machinelearning-configuration-caseclassif-prev
      path: /rest/organizations/{organizationId}/machinelearning/configuration/caseclassif/preview
      operations:
      - name: getdocumentscountpreview1
        method: POST
        description: Get Preview for Building a CC Model.
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `mycoveocloudv2organizationg8tp8wu3`
          required: true
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
