naftiko: 1.0.0-alpha2
info:
  label: Coveo Machine Learning Configuration API — Smart Snippets Configuration
  description: 'Coveo Machine Learning Configuration API — Smart Snippets Configuration. 3 operations. Lead operation: Get
    SS Content Fields. Self-contained Naftiko capability covering one Coveo business surface.'
  tags:
  - Coveo
  - Machine Learning Configuration
  - Smart Snippets Configuration
  created: '2026-05-19'
  modified: '2026-05-19'
binds:
- namespace: env
  keys:
    COVEO_API_KEY: COVEO_API_KEY
capability:
  consumes:
  - type: http
    namespace: ml-config-smart-snippets-configuration
    baseUri: https://platform.cloud.coveo.com
    description: Coveo Machine Learning Configuration API — Smart Snippets Configuration business capability. Self-contained,
      no shared references.
    authentication:
      type: bearer
      token: '{{env.COVEO_API_KEY}}'
    resources:
    - name: rest-organizations-organizationId-machinelearning-configuration-smartsnippets-co
      path: /rest/organizations/{organizationId}/machinelearning/configuration/smartsnippets/contentfields
      operations:
      - name: getcontentfields
        method: POST
        description: Get SS Content Fields
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `mycoveocloudv2organizationg8tp8wu3`
          required: true
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
    - name: rest-organizations-organizationId-machinelearning-configuration-smartsnippets-do
      path: /rest/organizations/{organizationId}/machinelearning/configuration/smartsnippets/documenttypes
      operations:
      - name: getdocumenttypes
        method: POST
        description: Get SS Document Types
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `mycoveocloudv2organizationg8tp8wu3`
          required: true
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
    - name: rest-organizations-organizationId-machinelearning-configuration-smartsnippets-pr
      path: /rest/organizations/{organizationId}/machinelearning/configuration/smartsnippets/preview
      operations:
      - name: getdocumentscountpreview
        method: POST
        description: Get Preview for Building an SS Model.
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: organizationId
          in: path
          type: string
          description: The unique identifier of the target [organization](https://docs.coveo.com/en/185/).<br />**Example:**
            `mycoveocloudv2organizationg8tp8wu3`
          required: true
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
