naftiko: 1.0.0-alpha2
info:
  label: Coveo Search Interface Service API — Search Page Configuration
  description: 'Coveo Search Interface Service API — Search Page Configuration. 14 operations. Lead operation: Get Project
    Search Page Interfaces. Self-contained Naftiko capability covering one Coveo business surface.'
  tags:
  - Coveo
  - Search Interface Service
  - Search Page Configuration
  created: '2026-05-19'
  modified: '2026-05-19'
binds:
- namespace: env
  keys:
    COVEO_SEARCH_TOKEN: COVEO_SEARCH_TOKEN
capability:
  consumes:
  - type: http
    namespace: search-interface-search-page-configuration
    baseUri: https://platform.cloud.coveo.com
    description: Coveo Search Interface Service API — Search Page Configuration business capability. Self-contained, no shared
      references.
    authentication:
      type: bearer
      token: '{{env.COVEO_SEARCH_TOKEN}}'
    resources:
    - name: organizations-organizationId-searchpage-v1-projects-interfaces
      path: /organizations/{organizationId}/searchpage/v1/projects/interfaces
      operations:
      - name: getprojectsearchpageinterfaces
        method: GET
        description: Get Project Search Page Interfaces
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
    - name: rest-organizations-organizationId-searchpage-v1-interfaces
      path: /rest/organizations/{organizationId}/searchpage/v1/interfaces
      operations:
      - name: getallsearchpageinterfaces
        method: GET
        description: Get All Search Page Interfaces
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
      - name: createsearchpageinterface
        method: POST
        description: Create a Search Page Interface
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
    - name: rest-organizations-organizationId-searchpage-v1-interfaces-interfaceId
      path: /rest/organizations/{organizationId}/searchpage/v1/interfaces/{interfaceId}
      operations:
      - name: getsearchpageinterface
        method: GET
        description: Get a Search Page Interface
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
      - name: updatesearchpageinterface
        method: PUT
        description: Update a Search Page Interface
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
      - name: deletesearchpageinterface
        method: DELETE
        description: Delete a Search Page Interface
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
    - name: rest-organizations-organizationId-searchpage-v1-interfaces-interfaceId-access-re
      path: /rest/organizations/{organizationId}/searchpage/v1/interfaces/{interfaceId}/access/request
      operations:
      - name: requestsearchpageinterfaceaccess
        method: POST
        description: Request Search Page Interface Access
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
    - name: rest-organizations-organizationId-searchpage-v1-interfaces-interfaceId-accesses
      path: /rest/organizations/{organizationId}/searchpage/v1/interfaces/{interfaceId}/accesses
      operations:
      - name: getsearchpageinterfaceaccess
        method: GET
        description: Get a Search Page Interface's Access Configuration
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
      - name: updatesearchpageinterfaceaccess
        method: PUT
        description: Update a Search Page Interface's Access Configuration
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
    - name: rest-organizations-organizationId-searchpage-v1-interfaces-interfaceId-accesses-
      path: /rest/organizations/{organizationId}/searchpage/v1/interfaces/{interfaceId}/accesses/users
      operations:
      - name: getsearchpageinterfaceuseraccess
        method: GET
        description: Get the List of Users with Access to the Search Page.
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
      - name: updatesearchpageinterfaceuseraccess
        method: PUT
        description: Update the List of Users with Access to a Search Page.
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
      - name: addsearchpageinterfaceuseraccess
        method: POST
        description: Add a Search Page Interface User Access
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
    - name: rest-organizations-organizationId-searchpage-v1-interfaces-interfaceId-pipelines
      path: /rest/organizations/{organizationId}/searchpage/v1/interfaces/{interfaceId}/pipelines
      operations:
      - name: getsearchpageinterfacepipelines
        method: GET
        description: Get Search Page Interface Pipelines
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
    - name: rest-organizations-organizationId-searchpage-v1-interfaces-interfaceId-preview
      path: /rest/organizations/{organizationId}/searchpage/v1/interfaces/{interfaceId}/preview
      operations:
      - name: previewsearchpageinterface
        method: POST
        description: Preview Search Page Interface
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
