naftiko: 1.0.0-alpha2
info:
  label: Coveo Source API — Salesforce Source Configuration
  description: 'Coveo Source API — Salesforce Source Configuration. 10 operations. Lead operation: Generate an ObjectsToGet
    Given a Schema. Self-contained Naftiko capability covering one Coveo business surface.'
  tags:
  - Coveo
  - Source
  - Salesforce Source Configuration
  created: '2026-05-19'
  modified: '2026-05-19'
binds:
- namespace: env
  keys:
    COVEO_API_KEY: COVEO_API_KEY
capability:
  consumes:
  - type: http
    namespace: source-salesforce-source-configuration
    baseUri: https://platform.cloud.coveo.com
    description: Coveo Source API — Salesforce Source Configuration business capability. Self-contained, no shared references.
    authentication:
      type: bearer
      token: '{{env.COVEO_API_KEY}}'
    resources:
    - name: rest-sourceconfiguration-salesforce-generateOTG
      path: /rest/sourceconfiguration/salesforce/generateOTG
      operations:
      - name: generateotg
        method: POST
        description: Generate an ObjectsToGet Given a Schema
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: schemaVersion
          in: query
          type: string
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
    - name: rest-sourceconfiguration-salesforce-objects
      path: /rest/sourceconfiguration/salesforce/objects
      operations:
      - name: getdefaultobjects
        method: GET
        description: Get Objects
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: accessToken
          in: query
          type: string
        - name: idUrl
          in: query
          type: string
        - name: refreshToken
          in: query
          type: string
        - name: refreshTokenGuid
          in: query
          type: string
        - name: schemaVersion
          in: query
          type: string
        - name: sandbox
          in: query
          type: boolean
        - name: serviceCloudIndexed
          in: query
          type: boolean
        - name: knowledgeIndexed
          in: query
          type: boolean
        - name: contentIndexed
          in: query
          type: boolean
        - name: chatterIndexed
          in: query
          type: boolean
        - name: cloudCrazeProductsIndexed
          in: query
          type: boolean
        - name: cloudCrazeOrdersIndexed
          in: query
          type: boolean
      - name: refreshobjects
        method: POST
        description: Refresh Objects
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: accessToken
          in: query
          type: string
        - name: idUrl
          in: query
          type: string
        - name: refreshToken
          in: query
          type: string
        - name: refreshTokenGuid
          in: query
          type: string
        - name: schemaVersion
          in: query
          type: string
        - name: sandbox
          in: query
          type: boolean
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
    - name: rest-sourceconfiguration-salesforce-objects-objectName
      path: /rest/sourceconfiguration/salesforce/objects/{objectName}
      operations:
      - name: getobject
        method: GET
        description: Get the Information for a Given Object
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: objectName
          in: path
          type: string
          required: true
        - name: accessToken
          in: query
          type: string
        - name: idUrl
          in: query
          type: string
        - name: refreshToken
          in: query
          type: string
        - name: refreshTokenGuid
          in: query
          type: string
        - name: schemaVersion
          in: query
          type: string
        - name: sandbox
          in: query
          type: boolean
    - name: rest-sourceconfiguration-salesforce-objects-objectName-fields
      path: /rest/sourceconfiguration/salesforce/objects/{objectName}/fields
      operations:
      - name: getfields
        method: GET
        description: Get Fields for a Given Object
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: objectName
          in: path
          type: string
          required: true
        - name: accessToken
          in: query
          type: string
        - name: idUrl
          in: query
          type: string
        - name: refreshToken
          in: query
          type: string
        - name: refreshTokenGuid
          in: query
          type: string
        - name: schemaVersion
          in: query
          type: string
        - name: sandbox
          in: query
          type: boolean
      - name: refreshfields
        method: POST
        description: Refresh Fields for a Given Object
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: objectName
          in: path
          type: string
          required: true
        - name: accessToken
          in: query
          type: string
        - name: idUrl
          in: query
          type: string
        - name: refreshToken
          in: query
          type: string
        - name: refreshTokenGuid
          in: query
          type: string
        - name: schemaVersion
          in: query
          type: string
        - name: sandbox
          in: query
          type: boolean
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
    - name: rest-sourceconfiguration-salesforce-objects-objectName-relationshipName
      path: /rest/sourceconfiguration/salesforce/objects/{objectName}/{relationshipName}
      operations:
      - name: getrelationship
        method: GET
        description: Get the Information for a Given Object Relationship
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: objectName
          in: path
          type: string
          required: true
        - name: relationshipName
          in: path
          type: string
          required: true
        - name: accessToken
          in: query
          type: string
        - name: idUrl
          in: query
          type: string
        - name: refreshToken
          in: query
          type: string
        - name: refreshTokenGuid
          in: query
          type: string
        - name: schemaVersion
          in: query
          type: string
        - name: sandbox
          in: query
          type: boolean
    - name: rest-sourceconfiguration-salesforce-parseOTG
      path: /rest/sourceconfiguration/salesforce/parseOTG
      operations:
      - name: parseotg
        method: POST
        description: Parse an ObjectsToGet to a Schema
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: schemaVersion
          in: query
          type: string
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
    - name: rest-sourceconfiguration-salesforce-schema
      path: /rest/sourceconfiguration/salesforce/schema
      operations:
      - name: getschema
        method: GET
        description: Get Complete Schema (objects and Fields)
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: accessToken
          in: query
          type: string
        - name: idUrl
          in: query
          type: string
        - name: refreshToken
          in: query
          type: string
        - name: refreshTokenGuid
          in: query
          type: string
        - name: schemaVersion
          in: query
          type: string
        - name: sandbox
          in: query
          type: boolean
        - name: serviceCloudIndexed
          in: query
          type: boolean
        - name: knowledgeIndexed
          in: query
          type: boolean
        - name: contentIndexed
          in: query
          type: boolean
        - name: chatterIndexed
          in: query
          type: boolean
        - name: cloudCrazeProductsIndexed
          in: query
          type: boolean
        - name: cloudCrazeOrdersIndexed
          in: query
          type: boolean
      - name: refreshschema
        method: POST
        description: Refresh Complete Schema (objects and Fields)
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: accessToken
          in: query
          type: string
        - name: idUrl
          in: query
          type: string
        - name: refreshToken
          in: query
          type: string
        - name: refreshTokenGuid
          in: query
          type: string
        - name: schemaVersion
          in: query
          type: string
        - name: sandbox
          in: query
          type: boolean
        - name: serviceCloudIndexed
          in: query
          type: boolean
        - name: knowledgeIndexed
          in: query
          type: boolean
        - name: contentIndexed
          in: query
          type: boolean
        - name: chatterIndexed
          in: query
          type: boolean
        - name: cloudCrazeProductsIndexed
          in: query
          type: boolean
        - name: cloudCrazeOrdersIndexed
          in: query
          type: boolean
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
